services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    command:
        -p 5432
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: passwd
        POSTGRES_DB: soundwave
